### ISSUE TITLE
Gradle Task :bootRun fails: Error: Could not find or load main class

### ISSUE THREAD

**Issue by eeriksp** [jhipster/jhipster-kotlin#115]
When running `./gradlew` on Windows 10  using JHipster  6.0.0-beta.0 for a newly created project, the script fails:

```
> Task :bootRun FAILED
Error: Could not find or load main class ...

FAILURE: Build failed with an exception.
```

When looking at the bootRun task:

```
    bootRun {
        dependsOn classpathJar
        doFirst {
            classpath = files("$buildDir/classes/java/main", "$buildDir/resources/main", classpathJar.archivePath)
        }
    }
```
it seems that the Kotlin directory is not included. I tried to add `"$buildDir/classes/kotlin/main"` at the beginning of the classpath, but although the needed class is clearly there, it made no difference.

Note that `./gradlew bootJar` produces a functional `.jar` file and running it with `java -jar build/libs/appname-0.0.1-SNAPSHOT.jar` works.

[ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
and are you using Java 8 or any other version?

**Comment by eeriksp** [comment]
Yes, I am using Java 8. I am not sure what you mean by Windows path issue.

Note that `./gradlew bootJar` produces a functional JAR file and running it with `java -jar build/libs/appname-0.0.1-SNAPSHOT.jar` works.

**Comment by pvliss** [comment]
@eeriksp I think you have hit the same issue as https://github.com/jhipster/generator-jhipster/issues/9572. This has been fixed in JHipster 6.0.0 final release. Can you please try and remove the whole block stating with `if (OperatingSystem.current().isWindows()) { ` and let us know if that works. See also   [here](https://github.com/jhipster/generator-jhipster/pull/9581/commits/acc2eb324e4feb8069a1afc7d1d6e421cbd88076) ) for reference.

**NOTE:** We should also remove the respective block from `kotlin.gradle.ejs` as well:
https://github.com/jhipster/jhipster-kotlin/blob/7130b5e96122f53641a72b6f661fd08a96300289/generators/server/templates/gradle/kotlin.gradle.ejs#L68-L73

**Comment by eeriksp** [comment]
Thank you!
This solved the problem :)

**Comment by pvliss** [comment]
@eeriksp Glad it did and thanks for reporting back!!!
