### ISSUE TITLE
Classes should be moved over from src/main/java to src/main/kotlin

### ISSUE THREAD

**Issue by tharakadesilva** [jhipster/jhipster-kotlin#13]

**Comment by thodorisbais** [comment]
I think we should either assign the/an `in-progress` label on this one, since @tharakadesilva has already started working on it.

**Comment by tharakadesilva** [comment]
I am actually having some issues getting the blueprint to run locally. I closed my PR till I get that resolved.

**Comment by thodorisbais** [comment]
@sendilkumarn after this and the discussions on #2 and #8 I think it's now official that we don't have any local setup (which we may need to add in the README, once fixed) of jhipster-kotlin yet.

However, @tharakadesilva , IMHO it would be better if you just left open/reopened your PR with a descriptive message (either WIP or a comment), so that other people interested in picking this issue up make clear somebody is already busy with that and don't waste meaningless time (since you already made some good progress), but we currently have other external dependencies to fix it.

**Comment by sendilkumarn** [comment]
@thodorisbais check out the detailed instructions added [here](https://github.com/jhipster/jhipster-kotlin#to-run-the-application-currently-till-jhipster-5-is-released)

And for spring-service and spring-controller, they are not the main generator as a whole. So it needs a bit of exploration and testing. 

@tharakadesilva AFAIK, you were able to solve it right using `npm` instead of `yarn`
