### ISSUE TITLE
[Suggestion] Keep existing JHipster java config code and use kotlin only for entities

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-kotlin#3]
As I currently understand it, this module is forking the entire server generator code and migrating it to Kotlin. But with this approach it will be highly likely that the blueprint will break in strange ways as the java code evolve without taking this module into account. The cost of maintaining two versions of the same code in different languages is high and especially as it's in different repos, we don't have visibility when changes in the main generator will cause dependent modules to break.

I would suggest to setup java compilation alongside kotlin with maven/gradle and keep most of the upstream backend code as java. After all this code is rarely changed and as there is not much logic there so it does no benefit too much from kotlin features.

Of course this could be offered as an option.

**Comment by sendilkumarn** [comment]
Good point @PierreBesson 

converting few thousand lines of code is really a big deal and it will change quite frequently.  While interoperability between Java and kotlin is really good, there are some corner cases that had to be handled and I am more worried about that part.  

Personally I would like  100% Kotlin project. But it seems to be wrong option to do at the moment (with many changes are pouring in from all the sides due to spring-boot-2).

It would be great to change the resource/service and domain + few config files into Kotlin and use them along with Java for the first release.

**Comment by jdubois** [comment]
@deepu105 @PierreBesson in fact this is the same issue as we have for reactive code, see my comment [here](https://github.com/jhipster/generator-jhipster/issues/5970#issuecomment-368249285). I think we should have a common approach.

**Comment by soberich** [comment]
Hi, I did not dig deep yet into the reasons you want to keep Java for config, but if by "config" you mean java `@Configuration` annotated java classes probably as a "fast moving project" and, that said, being progressive and staying on the "edge" of available technologies maybe jhipster should consider ti use functional bean definitions for kotlin which seems more in line with `jhipster-kotlin` as well as cleans up the code. I always thought that `config` package in any spring project is quite a tie.
Here is the commit https://github.com/spring-projects/spring-framework/commit/1f011467b8b929928963486f8594eea460b50eb7
and here is Spring Fu project https://github.com/spring-projects/spring-fu
