### ISSUE TITLE
Kotlin blueprint in docker (after npm install) reports no kotlin generator

### ISSUE THREAD

**Issue by timmles** [jhipster/jhipster-kotlin#51]
Overview of the issue
When using docker for the JHipster generation step, then installing the kotlin generator from npm, and running the kotlin blueprint, JHipster reports that there is no server or common blueprint and falls back to the default generator, only producing Java files.

Motivation for or Use Case
1) This is a supported method from the JHipster project.
2) I work on a couple Java, Kotlin and JS/npm projects, so I like to keep all my dev envs in docker so that I don't get global dependency issues when installed globally.

Reproduce the error

- mkdir ~/jhipster
- docker container run --name jhipster -v ~/jhipster:/home/jhipster/app -v ~/.m2:/home/jhipster/.m2 -p - 8080:8080 -p 9000:9000 -p 3001:3001 -d -t jhipster/jhipster
- docker container exec -it jhipster bash
  - (inside the container)
  - npm install -g generator-jhipster-kotlin
  - jhipster --blueprint kotlin

Related issues
None that I could find

Link to PR (if any)

JHipster Version(s)
5.6.0 (experienced in 5.5 as well)

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by timmles** [comment]
![screenshot from 2018-11-05 12-11-28](https://user-images.githubusercontent.com/3469626/47992401-7a674e00-e0f5-11e8-9728-f45acfcfd88a.png)

**Comment by timmles** [comment]
P.S. Feels like this is a n00b issue, so I hesitated before creating this issue - if it is, I'd like to improve the documentation to assist more people getting onto the project and testing it.
P.P.S. I did try joining the Slack, but looks like an invite is needed and not sure how to go about that.

**Comment by sendilkumarn** [comment]
@timmles Thanks for the issue. I think you need to do `npm link generator-jhipster-kotlin` here. Also the current generator only supports `v5.3.0`. Since there was a lot of changes happened between 5.3 and 5.6 we haven't implemented those changes.

P.s. Why you need to link? Basically adding only `generator-jhipster-kotlin` is enough. Because that would add a wrapper around the `JHipster`. Since you are calling the global `jhipster` which don't know anything about the `kotlin-module` Hope that clarifies. 

> I'd like to improve the documentation to assist more people getting onto the project and testing it.

Would be super cool to add this "Docker" generation steps in the readme 👍

**Comment by sendilkumarn** [comment]
Hope that will solve the problem, please feel free to re-open the issue if it is still there. 

Based on the PR #52 - you can use the Current JHipster Master.
