### ISSUE TITLE
Update to Kotlin version 1.2.71

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/jhipster-kotlin#62]
This should be an easier to upgrade, we have to check both gradle and maven based app works

**Comment by sendilkumarn** [comment]
@pvliss go for it. Yeah we will move forward with this project for sure

**Comment by pvliss** [comment]
Nice. Thanks!!! Will provide the PF in a while

**Comment by pvliss** [comment]
@sendilkumarn  So I created the PR and no change other than simply upgrading the version was needed.

One thing I noted though when I generated a new project using Gradle is that no Kotlin source was generated. The build.gradle was generated as expected. With maven everything worked as expected.

I am looking at [files.js](https://github.com/jhipster/jhipster-kotlin/blob/master/generators/server/files.js) but I can not find anything wrong in there. Also new at yeoman and ejs :)

BTW,  I am also thinking to create several tickets such as : 
- Upgrade Kotlin to 1.3.11
- Upgrade to JHipster 5.7.2
- Apply IDEA code inspections (e.g.  make primary constructor, use template instead of concatenation,etc.)
- Start converting more Java code to Kotlin
- etc.

Is that ok with you?

**Comment by sendilkumarn** [comment]
> Upgrade Kotlin to 1.3.11

I am not sure whether that will work with Spring Boot 2.0.7. There was some problem when I tried it before. 

> Upgrade to JHipster 5.7.2

Sure go for it. I hope it will work with the master branch wit no issues


>Start converting more Java code to Kotlin

This is one of the major concern for me, if we convert the files then we have to keep up with JHipster's pace. But we don't have that many contributors here to compete with that. I would say we can wait a bit on here. Rather start with Entity generator.

**Comment by pvliss** [comment]
> > Upgrade Kotlin to 1.3.11
> 
> I am not sure whether that will work with Spring Boot 2.0.7. There was some problem when I tried it before.
> 

I have just tested and found the cause. Will comment on newly created ticket #69. But will prefer if #69 gets merged before submitting a PR to avoid rebasing ,etc.  

> > Upgrade to JHipster 5.7.2
> 
> Sure go for it. I hope it will work with the master branch wit no issues

Ok. Will get to that to. Created new ticket #70

> 
> > Start converting more Java code to Kotlin
> 
> This is one of the major concern for me, if we convert the files then we have to keep up with JHipster's pace. But we don't have that many contributors here to compete with that. I would say we can wait a bit on here. Rather start with Entity generator.

I guess you are right. I mean I currently have a lot of time and plan to contribute a lot the next few weeks but it can be a problem with future maintenance. Nevertheless, I believe once the project gets more production ready more people will be interested and start contributing, hopefully. I will see if I can start with the entity generator then.
