### ISSUE TITLE
Migrate Spring service generator into Kotlin

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/jhipster-kotlin#8]

**Comment by thodorisbais** [comment]
Hello,

I think this is a good chance for me to learn two things (JHipster & Kotlin) at once by doing and to also stay up-to-date with the front-end related trends; _the latter also implies upcoming question(s) might be really trivial, but I think it's better to ask early 😃 ._

On topic, although this seems a pretty easy one, I think I am missing some very basic configuration.
After linking the cloned `generator-jhipster-kotlin` repo to the local project I am using for testing purposes (e.g. `jhipster-kotlin-tests`), trying to run a test command like `generator-jhipster-kotlin server` returns the common error: `-bash: jhipster-kotlin: command not found`.

Initially, I thought this was a PATH related problem, since this is the symbolic link that was created after linking and `/usr/local/lib/node_modules/` is not part of my PATH (I am using MacOS):

```
/usr/local/lib/node_modules/generator-jhipster-kotlin -> /Users/thodoris/git/jhipster-kotlin
```

So, I tested again the command inside `/usr/local/lib/node_modules/generator-jhipster-kotlin` directory and the error persists.

Other things I thought might be related, but I am not sure:
- I noticed in the changelog a mention that now it only runs with maven
- We don't have a cli directory for this project yet

I think I am missing some very basic setup here, do you have any idea?

Thodoris

**Comment by sendilkumarn** [comment]
You have to clone the latest `generator-JHipster` repo and then link `yarn link` in that folder.
Followed by running `yarn link generator-jhipster` inside `jhipster-kotlin-tests` folder

and you have to run `jhipster --blueprint generator-jhipster-kotlin`

> I noticed in the changelog a mention that now it only runs with maven

it runs on gradle too now

**Comment by sendilkumarn** [comment]
Closing this since the PR is merged
